[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
eclipse_ns = "DrQi9GDgAnrAjCjuJXQZqLjJ7mHr7uW9nFpTCzTPmt7K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://staging-rpc.dev.eclipsenetwork.xyz"
wallet = "/Users/pratham/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
